# This workflow will build a .NET project
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-net

name: .NET

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Setup .NET
      uses: actions/setup-dotnet@v3
      with:
        dotnet-version: 4.7.2
    - name: Restore dependencies
      run: dotnet restore C3296512_Assign2/C3296512_Assign1/C3296512_Assign1.csproj
    - name: Build
      run: dotnet build C3296512_Assign2/C3296512_Assign1/C3296512_Assign1.csproj --no-restore
    - name: Test
      run: dotnet test C3296512_Assign2/C3296512_Assign1/C3296512_Assign1.csproj --no-build --verbosity normal
